### ISSUE TITLE
'deeplabv3_xception_tf_dim_ordering_tf_kernels.h5' weights can not be loaded

### ISSUE THREAD

**Issue by liuyexin** [rezazad68/AttentionDeeplabv3p#2]
ValueError: You are trying to load a weight file containing 293 layers into a model with 321 layers.

**Comment by rezazad68** [comment]
Thanks for your message. When you are loading the weights please use the flag `by_name=True`. We built our model on top of the Deeplabv3+, thus, new layers included in the model structure which requires loading weights by layer names.
